#!/bin/bash

# Pass the password in the block instance

case $BLOCK_BUTTON in
    3) echo 'Updating to Office Docked' && bash ~/.screenlayout/office_docked.sh ;;  # right click, pause/unpause
    4) echo 'Updating to Office Docked' && bash ~/.screenlayout/office_docked.sh ;;  # scroll up, previous
    5) echo 'Updating to Laptop' && bash ~/.screenlayout/laptop.sh ;;  # scroll down, next
    *) echo 'DISPLAY';;
esac